### ISSUE TITLE
Fix csv parsing errors that occur with small files

### ISSUE THREAD

**Issue by jeffkole** [lisad/phaser#105]
The specific errors that occur are documented in [test_csv.py#test_single_row_col_csv](https://github.com/lisad/phaser/blob/212989c978c2820938c0a966e8ee6d5239e6dd1e/tests/test_csv.py#L88).  I believe they are the result of not having enough data for clevercsv to detect the format.  It seems that a space in a field causes a problem.

**Comment by lisad** [comment]
The test got lost so we need to re-add it and test to close this issue
