### ISSUE TITLE
Steps should always get COPY of data to protect foot/gun incidents

### ISSUE THREAD

**Issue by lisad** [lisad/phaser#19]
When the phase calls each step it can pass a copy of the row, or a copy of the batch data.  

If the step modifies the copy and returns it, that is no problem.

**Comment by jeffkole** [comment]
I believe this is done for `row_steps` at least in [phase.py#L91](https://github.com/lisad/phaser/blob/649ea7b87c3fe0cb50a895d89164787a026ca304/phaser/phase.py#L91)

Will `deepcopy` work sufficiently well for batch and data frame steps? Do we want it to?

**Comment by jeffkole** [comment]
Data frames and batches are allowed to be modified.
