### ISSUE TITLE
Index rows starting at 1

### ISSUE THREAD

**Issue by lisad** [lisad/phaser#67]
I feel like there may be no "right" thing here, but I'd like to index rows starting with 1.  When we report on rows in dropped rows, errors, warnings - indexing from 0 means that line numbers are 2 off of what you'd see in a file (because the header row is line 1 in the file, and the first data row is line 2, so that means that "row number 1" is the 3rd line.)

I suppose there's even an argument for reporting errors and warnings on file line number, hehheh.  But I prefer row 1 is the first data row, and the last data row number is the same as the total number of rows
WDYT?

**Comment by lisad** [comment]
@jeffkole for your comment

**Comment by jeffkole** [comment]
Yes I think row number 1 as the first data line makes tons of sense.

**Comment by lisad** [comment]
Resolved by #71
